In [ ]:
1. Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

In [ ]:
# imports

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats
from pydataset import data
from env import usr,pw,host
from sqlalchemy import create_engine

In [3]:
conf_interval = 0.95
alpha = 1 - conf_interval

In [4]:
df = pd.read_clipboard()

In [6]:
contingency = pd.DataFrame({'codeup_student': [49,1], 'not_codeup': [20,30]}, index=['uses_macbook', 'not_macbook'])

In [7]:
contingency

codeup_student  not_codeup
uses_macbook              49          20
not_macbook                1          30

In [ ]:
# H0: Macbook Usage is independent of being a Codeup Student

In [ ]:
# make our computation

In [9]:
chi2, p, degf, expected = stats.chi2_contingency(contingency)

print('Observed\n:')
print(contingency.values)
print('------------------------\nExpected: \n')
print(expected)
print('------------------------\n')
print(f'chi2 = {chi2:.4f}')
print(f'p value: {p:.8f}')
if p < alpha:
      print('We can reject the null hypothesis')

Observed
:
[[49 20]
 [ 1 30]]
------------------------
Expected: 

[[34.5 34.5]
 [15.5 15.5]]
------------------------

chi2 = 36.6526
p value: 0.00000000
We can reject the null hypothesis


In [ ]:
# We have a low p, and we can reject the null hypothesis, suggesting that macbook usage may be dependent on current codeup matriculation

### 2. Choose another 2 categorical variables from the mpg dataset and perform a chi2 contingency table test with them. Be sure to state your null and alternative hypotheses.

In [ ]:
# load up our mpg data

In [10]:
df = data('mpg')

In [12]:
data('mpg', show_doc=True)

mpg

PyDataset Documentation (adopted from R Documentation. The displayed examples are in R)

## Fuel economy data from 1999 and 2008 for 38 popular models of car

### Description

This dataset contains a subset of the fuel economy data that the EPA makes
available on http://fueleconomy.gov. It contains only models which had a new
release every year between 1999 and 2008 - this was used as a proxy for the
popularity of the car.

### Usage

    data(mpg)

### Format

A data frame with 234 rows and 11 variables

### Details

  * manufacturer. 

  * model. 

  * displ. engine displacement, in litres 

  * year. 

  * cyl. number of cylinders 

  * trans. type of transmission 

  * drv. f = front-wheel drive, r = rear wheel drive, 4 = 4wd 

  * cty. city miles per gallon 

  * hwy. highway miles per gallon 

  * fl. 

  * class. 




In [ ]:
# pick our two categoricals

In [13]:
a = df.manufacturer
b = df.drv

In [14]:
a.value_counts()

dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64

In [15]:
b.value_counts()

f    106
4    103
r     25
Name: drv, dtype: int64

## What is our null Hypothesis?

### H0: Make or Manufacturer is indepenent of the drivetrain type on vehicles

In [ ]:
# run our chi squared contingency:

In [16]:
observed = pd.crosstab(a,b)

In [17]:
observed

drv            4   f   r
manufacturer            
audi          11   7   0
chevrolet      4   5  10
dodge         26  11   0
ford          13   0  12
honda          0   9   0
hyundai        0  14   0
jeep           8   0   0
land rover     4   0   0
lincoln        0   0   3
mercury        4   0   0
nissan         4   9   0
pontiac        0   5   0
subaru        14   0   0
toyota        15  19   0
volkswagen     0  27   0

In [18]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

print('Observed\n:')
print(observed.values)
print('------------------------\nExpected: \n')
print(expected)
print('------------------------\n')
print(f'chi2 = {chi2:.4f}')
print(f'p value: {p:.8f}')
if p < alpha:
      print('We can reject the null hypothesis')

Observed
:
[[11  7  0]
 [ 4  5 10]
 [26 11  0]
 [13  0 12]
 [ 0  9  0]
 [ 0 14  0]
 [ 8  0  0]
 [ 4  0  0]
 [ 0  0  3]
 [ 4  0  0]
 [ 4  9  0]
 [ 0  5  0]
 [14  0  0]
 [15 19  0]
 [ 0 27  0]]
------------------------
Expected: 

[[ 7.92307692  8.15384615  1.92307692]
 [ 8.36324786  8.60683761  2.02991453]
 [16.28632479 16.76068376  3.95299145]
 [11.0042735  11.32478632  2.67094017]
 [ 3.96153846  4.07692308  0.96153846]
 [ 6.16239316  6.34188034  1.4957265 ]
 [ 3.52136752  3.62393162  0.85470085]
 [ 1.76068376  1.81196581  0.42735043]
 [ 1.32051282  1.35897436  0.32051282]
 [ 1.76068376  1.81196581  0.42735043]
 [ 5.72222222  5.88888889  1.38888889]
 [ 2.2008547   2.26495726  0.53418803]
 [ 6.16239316  6.34188034  1.4957265 ]
 [14.96581197 15.4017094   3.63247863]
 [11.88461538 12.23076923  2.88461538]]
------------------------

chi2 = 232.0345
p value: 0.00000000
We can reject the null hypothesis


## 3. Use the data from the employees database to answer these questions:

### Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)


In [19]:
#  gender: department (marketing or sales)
# current employees only
# 
# tables needed:
# employees
# dept_emp
# departments

In [20]:
# set up sql connection

In [21]:
def get_connection(db, user, host, password):
    url = f'mysql+pymysql://{user}:{password}@{host}/{db}'
    return create_engine(url)

In [22]:
conn = get_connection('employees', usr, host, pw)

In [23]:
db = 'employee'

In [24]:
# make our query for the parameters that we want:

In [25]:
query = '''SELECT e.gender, d.dept_name
FROM employees AS e
JOIN dept_emp as dn ON dn.emp_no = e.emp_no
AND to_date > CURDATE()
JOIN departments AS d ON dn.dept_no = d.dept_no'''

In [26]:
# load up our data

In [27]:
gender_dept = pd.read_sql(query, conn)

In [28]:
gender_dept

gender         dept_name
0           M  Customer Service
1           F  Customer Service
2           M  Customer Service
3           F  Customer Service
4           F  Customer Service
...       ...               ...
240119      F             Sales
240120      M             Sales
240121      M             Sales
240122      F             Sales
240123      F             Sales

[240124 rows x 2 columns]

In [ ]:
# restrict that to just sales and marketing

In [29]:
gender_dept = gender_dept[(gender_dept.dept_name == 'Sales') | (gender_dept.dept_name == 'Marketing')]

In [ ]:
# make our crosstab for observed values

In [30]:
observed = pd.crosstab(gender_dept.gender, gender_dept.dept_name)

In [31]:
observed

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [32]:
# HO gender of the employee is independent to department of marketing or sales

In [34]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

print('Observed\n:')
print(observed.values)
print('------------------------\nExpected: \n')
print(expected)
print('------------------------\n')
print(f'chi2 = {chi2:.4f}')
print(f'p value: {p:.8f}')
if p < alpha:
      print('We can reject the null hypothesis')

Observed
:
[[ 5864 14999]
 [ 8978 22702]]
------------------------
Expected: 

[[ 5893.2426013 14969.7573987]
 [ 8948.7573987 22731.2426013]]
------------------------

chi2 = 0.3240
p value: 0.56919386


#### Is an employee's gender independent of whether or not they are or have been a manager?

In [ ]:
# set up a new query for this data. we want:
# 
# employee gender, manager status
# 
# tables needed: employees, dept_manager

In [37]:
query = '''SELECT e.emp_no, e.gender, dm.dept_no
FROM employees as e
LEFT JOIN dept_manager AS dm ON e.emp_no = dm.emp_no'''

In [36]:
# load up our dataframe from our query

In [38]:
gender_manager = pd.read_sql(query, conn)

In [39]:
gender_manager

emp_no gender dept_no
0        10001      M    None
1        10002      F    None
2        10003      M    None
3        10004      M    None
4        10005      M    None
...        ...    ...     ...
300019  499995      F    None
300020  499996      M    None
300021  499997      M    None
300022  499998      M    None
300023  499999      M    None

[300024 rows x 3 columns]

In [ ]:
# rename that column and fill the na's

In [40]:
gender_manager = gender_manager.rename(columns={'dept_no': 'manager'}).fillna(0)

In [41]:
# run an apply function to make manager status a binaryu

In [43]:
gender_manager['manager'] = gender_manager['manager'].apply(lambda x: x if x == 0 else 1)

In [44]:
gender_manager.manager.value_counts()

0    300000
1        24
Name: manager, dtype: int64

In [45]:
observed = pd.crosstab(gender_manager['gender'], gender_manager['manager'])

In [46]:
observed

manager       0   1
gender             
F        120038  13
M        179962  11

In [ ]:
# H0: Employee Gender is independent of history in management

In [47]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

print('Observed\n:')
print(observed.values)
print('------------------------\nExpected: \n')
print(expected)
print('------------------------\n')
print(f'chi2 = {chi2:.4f}')
print(f'p value: {p:.8f}')
if p < alpha:
      print('We can reject the null hypothesis')

Observed
:
[[120038     13]
 [179962     11]]
------------------------
Expected: 

[[1.20041397e+05 9.60331174e+00]
 [1.79958603e+05 1.43966883e+01]]
------------------------

chi2 = 1.4567
p value: 0.22745819
